import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "./Component/NavBar";
import Footer from "./Component/Footer";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">

      <body className={`${inter.className} `}>

        <div className="px-4">
          <NavBar />
          {children}
        </div>
        <Footer />
      </body>

    </html>
  );
}
